# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: redis-service-node
  labels:
    app: redis
spec:
  ports:
  - name: redis-port
    port: 6379
    nodePort: 6379
  selector:
    app: redis
    appCluster: redis-cluster
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
spec:
  ports:
  - name: redis-svc
    port: 6379
  clusterIP: None
  selector:
    app: redis-cluster
